# Uses the Makefile to build all .typ files to .pdf files

name: Compile to PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository.
        uses: actions/checkout@v3

      - name: Restore cached package downloads
        id: cache-packages-restore
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/.cache/typst
          key: cached-packages
          restore-keys: |
            cached-packages-

      - name: Compile Typst to PDF.
        uses: addnab/docker-run-action@v3
        with:
          # typst has an official container image based an Alpine
          image: ghcr.io/typst/typst:latest
          options: -v ${{ github.workspace }}:/root/work -v ${{github.workspace }}/.cache:/root/.cache
          # which doesn't have make by default, so it needs to be added
          run: |
            apk add make

            cd /root/work
            make clean
            make all

      - name: Cache package downloads
        id: cache-packages-save
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/.cache/typst
          key: cached-packages-${{ hashFiles('.cache/typst/**/*') }}

      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: ./**/*.pdf
